---
# Debian tasks file for auto_pkg_updates

- name: Update apt package cache.
  apt:
    update_cache: true
    cache_valid_time: 600

- name: Install unattended-upgrades package.
  package:
    name: unattended-upgrades
    state: present

- name: Copy unattended-upgrades configuration files.
  template:
    src: "etc/apt/apt.conf.d/{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10periodic
    - 50unattended-upgrades
