---
# RedHat 8 tasks file for auto_pkg_updates

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

- name: Define auto_pkg_updates_config_path.
  set_fact:
    auto_pkg_updates_config_path: "{{ __auto_pkg_updates_config_path }}"
    when: auto_pkg_updates_config_path is not defined

- name: Install dnf-automatic package.
  package:
    name: dnf-automatic
    state: present
    update_cache: true

- name: Configure dnf-automatic.
  lineinfile:
    dest: "{{ auto_pkg_updates_config_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backup: true
  with_items:
    - regexp: "^upgrade_type = .+"
      line: "upgrade_type = {{ auto_pkg_updates_upgrade_type }}"
    - regexp: "^apply_updates = .+"
      line: "apply_updates = {{ auto_pkg_updates_apply_updates }}"
  notify: Restart dnf-automatic service

- name: Ensure dnf-automatic is running and enabled on boot.
  service:
    name: "{{ auto_pkg_updates_service_name }}"
    state: started
    enabled: true
