---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all

  tasks:

    - name: Include OS-specific tasks.
      include_tasks: "{{ item }}"
      with_first_found:
        - "tests/{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "tests/{{ ansible_facts['distribution'] }}.yml"
        - "tests/{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "tests/{{ ansible_facts['os_family'] }}.yml"
